[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]
solc = "0.8.20"
evm_version = 'paris'

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
sepolia = "https://rpc.sepolia.dev"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
